name: Test & Build
on:
  - push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install Go
        id: install-go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install Python
        id: install-python
        uses: actions/setup-python@v5

      - name: Install Terraform
        id: install-terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.2

      - name: Install TFLint
        id: install-tflint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.52.0

      - name: Run pre-commit
        id: install-pre-commit
        uses: pre-commit/action@v3.0.1

  build-and-test:
    name: Build & Test
    strategy:
      fail-fast: false
      matrix:
        go-version: [stable, oldstable]
        os: [ubuntu-latest]  # [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v4

      - name: Install Go
        id: install-go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - run: go build .
      - run: go test ./...
