---
name: Test & Build
on:
  push:
    branches:
      - "**"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python
        id: install-python
        uses: actions/setup-python@v5

      - name: Install Go
        id: install-go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Setup Tools Cache
        id: setup-cache-tools
        uses: actions/cache@v4
        with:
          path: ~/.config/toolshare/cache
          key: tool-binaries|${{ runner.os }}|${{ runner.arch }}|${{ hashFiles('.toolshare.yaml') }}
          restore-keys: tool-binaries|${{ runner.os }}|${{ runner.arch }}|

      - name: Setup Pre-Commit Cache
        id: setup-cache-pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ runner.os }}|${{ runner.arch }}|${{ hashFiles('.pre-commit-config.yaml', '.python-version') }}  # yamllint disable-line rule:line-length
          restore-keys: pre-commit-3|${{ runner.os }}|${{ runner.arch }}|

      - name: Setup Toolshare
        id: setup-toolshare
        run: ./scripts/setup_toolshare.sh

      - name: Run pre-commit
        id: run-pre-commit
        run: pre-commit run --show-diff-on-failure --color=always

  build-and-test:
    name: Build & Test
    strategy:
      fail-fast: false
      matrix:
        go-version: [stable, oldstable]
        os: [ubuntu-latest]  # [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v4

      - name: Install Go
        id: install-go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - run: go build .
      - run: go test ./...
