---
name: Deploy Infra
on:
  push:
    branches:
      - '**'

env:
  TF_VAR_github_owner: ${{ github.repository_owner }}
  TF_VAR_github_owner_id: ${{ github.repository_owner_id }}
  TF_VAR_github_slug: ${{ github.repository }}
  TF_VAR_google_project_id: ${{ vars.google_project_id }}

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Go
        id: install-go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Setup Toolshare
        id: setup-toolshare
        run: ./scripts/setup_toolshare.sh

      - name: Authenticate GCP
        id: auth-gcp
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          workload_identity_provider: projects/${{ vars.google_project_number }}/locations/global/workloadIdentityPools/ci-automation/providers/github # yamllint disable-line rule:line-length
          service_account: toolshare-ci@${{ vars.google_project_id }}.iam.gserviceaccount.com

      - name: Plan - Bootstrap
        id: plan-bootstrap
        run: scripts/terraform.sh terraform/bootstrap plan

      - name: Plan - CI Infra
        id: plan-ci-infra
        run: scripts/terraform.sh terraform/ci-infra plan

      - name: Upload Artefacts
        id: upload-artefacts
        uses: actions/upload-artifact@v4
        if: ${{ steps.plan-bootstrap.outputs.changes || steps.plan-ci-infra.outputs.changes }}
        with:
          name: terraform-plans
          path: "*.tfplan"
          retention-days: 1 # We don't want to keep potentially stale plans around for long.
          if-no-files-found: ignore

    outputs:
      bootstrap_changes: ${{ steps.plan-bootstrap.outputs.changes }}
      ci_infra_changes: ${{ steps.plan-ci-infra.outputs.changes }}

  apply:
    name: Apply
    needs: plan
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    if: |-
      ${{
        github.ref == 'refs/heads/main' &&
        (needs.plan.outputs.bootstrap_changes || needs.plan.outputs.ci_infra_changes)
      }}
    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Go
        id: install-go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Setup Toolshare
        id: setup-toolshare
        run: ./scripts/setup_toolshare.sh

      - name: Authenticate GCP
        id: auth-gcp
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ vars.google_project_id }}
          workload_identity_provider: projects/${{ vars.google_project_number }}/locations/global/workloadIdentityPools/ci-automation/providers/github # yamllint disable-line rule:line-length
          service_account: toolshare-ci@${{ vars.google_project_id }}.iam.gserviceaccount.com
          create_credentials_file: true
          export_environment_variables: true

      - name: Install gcloud
        id: install-gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Download Artefacts
        id: download-artefacts
        uses: actions/download-artifact@v4
        with:
          name: terraform-plans

      - name: Apply - Bootstrap
        id: run-apply-bootstrap
        if: ${{ needs.plan.outputs.bootstrap_changes }}
        run: scripts/terraform.sh terraform/bootstrap apply -auto-approve

      - name: Apply - CI Infra
        id: run-apply-ci-infra
        if: ${{ needs.plan.outputs.ci_infra_changes }}
        run: scripts/terraform.sh terraform/ci-infra apply -auto-approve
