---
name: Release
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Go
        id: install-go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Setup Toolshare
        id: setup-toolshare
        run: ./scripts/setup_toolshare.sh

      - name: Run GoReleaser
        id: run-goreleaser
        run: goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
